language: python
python:
#  - "3.2" # contextlib issue, at least
#  - "3.3" # contextlib issue, at least
  - "3.4"
  - "3.5.0"
  - "3.5"
  - "3.5-dev"
#  - "nightly" # broken for several nights in a row

install: "pip install -r requirements.txt"

script:
  make test_coverage
after_success:
  coveralls
