#to get 14.04:
#sudo: required
#dist: trusty

language: python
python:
#  - "3.2"
#  - "3.3" # contextlib, re.findall
#  - "3.4" # subprocess.run
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

install: "pip install -r requirements.txt"

script:
  make test_coverage
after_success:
  coveralls
