language: python
sudo: true
dist: xenial

python:
#  - 3.2
#  - 3.3 # contextlib, re.findall
#  - 3.4 # subprocess.run
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.9-dev
  - python: nightly
  include:
  - python: 3.5
    arch: arm64
  - python: 3.5
    arch: ppc64le
  - python: 3.5
    arch: s390x

git:
  depth: 99999

install: "pip install -r requirements.txt"

script:
  make test_coverage
after_success:
  coveralls
