language: python
python:
#  - "3.2" # contextlib/findall, at least
#  - "3.3" # contextlib/findall, at least
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # working for now

install: "pip install -r requirements.txt"

script:
  make test_coverage
#after_success:
#  coveralls
