language: python
sudo: true
dist: xenial

python:
#  - 3.2
#  - 3.3 # contextlib, re.findall
#  - 3.4 # subprocess.run
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - python: nightly
  - python: 3.5
    arch: arm64
  - python: 3.5
    arch: s390x
  include:
  - python: 3.5
    arch: arm64  # 3.5x normal build time
  - python: 3.5
    arch: s390x  # 2x normal build time

git:
  depth: 99999

before_install:
  # temporary workaround for s390x and arm64 permissions problem
  # https://travis-ci.community/t/permission-issue-while-building-wheels-for-various-python-packages/7822/12
  # currently needed for s390x and not arm64?
  - sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels || true

install: "pip install -r requirements.txt"

script:
  make test_coverage
after_success:
  coveralls
