language: python
python:
#  - 3.2
#  - 3.3 # contextlib, re.findall
#  - 3.4 # subprocess.run
  - 3.5
  - 3.6
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.7
  - python: nightly
  include:
  - python: 3.7
    sudo: true
    dist: xenial

git:
  depth: 99999

install: "pip install -r requirements.txt"

script:
  make test_coverage
after_success:
  coveralls
